# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := Nucleo_usbhost_quadrature_encoder


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += USBHOST/USBHost/TARGET_STM/USBEndpoint_STM.o
OBJECTS += USBHOST/USBHost/TARGET_STM/USBHALHost_STM.o
OBJECTS += USBHOST/USBHost/USBDeviceConnected.o
OBJECTS += USBHOST/USBHost/USBEndpoint.o
OBJECTS += USBHOST/USBHost/USBHALHost_LPC17.o
OBJECTS += USBHOST/USBHost/USBHALHost_M451.o
OBJECTS += USBHOST/USBHost/USBHALHost_NUC472.o
OBJECTS += USBHOST/USBHost/USBHALHost_RZ_A1.o
OBJECTS += USBHOST/USBHost/USBHost.o
OBJECTS += USBHOST/USBHost3GModule/WANDongle.o
OBJECTS += USBHOST/USBHost3GModule/WANDongleSerialPort.o
OBJECTS += USBHOST/USBHostHID/USBHostKeyboard.o
OBJECTS += USBHOST/USBHostHID/USBHostMouse.o
OBJECTS += USBHOST/USBHostHID/USBHostSteamController.o
OBJECTS += USBHOST/USBHostHub/USBHostHub.o
OBJECTS += USBHOST/USBHostMIDI/USBHostMIDI.o
OBJECTS += USBHOST/USBHostMSD/USBHostMSD.o
OBJECTS += USBHOST/USBHostSerial/USBHostSerial.o
OBJECTS += main.o
OBJECTS += mbed-os/drivers/AnalogIn.o
OBJECTS += mbed-os/drivers/BusIn.o
OBJECTS += mbed-os/drivers/BusInOut.o
OBJECTS += mbed-os/drivers/BusOut.o
OBJECTS += mbed-os/drivers/CAN.o
OBJECTS += mbed-os/drivers/Ethernet.o
OBJECTS += mbed-os/drivers/FileBase.o
OBJECTS += mbed-os/drivers/FilePath.o
OBJECTS += mbed-os/drivers/FileSystemLike.o
OBJECTS += mbed-os/drivers/FlashIAP.o
OBJECTS += mbed-os/drivers/I2C.o
OBJECTS += mbed-os/drivers/I2CSlave.o
OBJECTS += mbed-os/drivers/InterruptIn.o
OBJECTS += mbed-os/drivers/InterruptManager.o
OBJECTS += mbed-os/drivers/LocalFileSystem.o
OBJECTS += mbed-os/drivers/RawSerial.o
OBJECTS += mbed-os/drivers/SPI.o
OBJECTS += mbed-os/drivers/SPISlave.o
OBJECTS += mbed-os/drivers/Serial.o
OBJECTS += mbed-os/drivers/SerialBase.o
OBJECTS += mbed-os/drivers/Stream.o
OBJECTS += mbed-os/drivers/Ticker.o
OBJECTS += mbed-os/drivers/Timeout.o
OBJECTS += mbed-os/drivers/Timer.o
OBJECTS += mbed-os/drivers/TimerEvent.o
OBJECTS += mbed-os/events/EventQueue.o
OBJECTS += mbed-os/events/equeue/equeue.o
OBJECTS += mbed-os/events/equeue/equeue_mbed.o
OBJECTS += mbed-os/events/equeue/equeue_posix.o
OBJECTS += mbed-os/features/filesystem/Dir.o
OBJECTS += mbed-os/features/filesystem/File.o
OBJECTS += mbed-os/features/filesystem/FileSystem.o
OBJECTS += mbed-os/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ccsbcs.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ff.o
OBJECTS += mbed-os/features/filesystem/fat/FATFileSystem.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += mbed-os/features/frameworks/unity/source/unity.o
OBJECTS += mbed-os/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/unity_handler.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_case.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_harness.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_types.o
OBJECTS += mbed-os/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += mbed-os/features/mbedtls/src/aes.o
OBJECTS += mbed-os/features/mbedtls/src/aesni.o
OBJECTS += mbed-os/features/mbedtls/src/arc4.o
OBJECTS += mbed-os/features/mbedtls/src/asn1parse.o
OBJECTS += mbed-os/features/mbedtls/src/asn1write.o
OBJECTS += mbed-os/features/mbedtls/src/base64.o
OBJECTS += mbed-os/features/mbedtls/src/bignum.o
OBJECTS += mbed-os/features/mbedtls/src/blowfish.o
OBJECTS += mbed-os/features/mbedtls/src/camellia.o
OBJECTS += mbed-os/features/mbedtls/src/ccm.o
OBJECTS += mbed-os/features/mbedtls/src/certs.o
OBJECTS += mbed-os/features/mbedtls/src/cipher.o
OBJECTS += mbed-os/features/mbedtls/src/cipher_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/cmac.o
OBJECTS += mbed-os/features/mbedtls/src/ctr_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/debug.o
OBJECTS += mbed-os/features/mbedtls/src/des.o
OBJECTS += mbed-os/features/mbedtls/src/dhm.o
OBJECTS += mbed-os/features/mbedtls/src/ecdh.o
OBJECTS += mbed-os/features/mbedtls/src/ecdsa.o
OBJECTS += mbed-os/features/mbedtls/src/ecjpake.o
OBJECTS += mbed-os/features/mbedtls/src/ecp.o
OBJECTS += mbed-os/features/mbedtls/src/ecp_curves.o
OBJECTS += mbed-os/features/mbedtls/src/entropy.o
OBJECTS += mbed-os/features/mbedtls/src/entropy_poll.o
OBJECTS += mbed-os/features/mbedtls/src/error.o
OBJECTS += mbed-os/features/mbedtls/src/gcm.o
OBJECTS += mbed-os/features/mbedtls/src/havege.o
OBJECTS += mbed-os/features/mbedtls/src/hmac_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/md.o
OBJECTS += mbed-os/features/mbedtls/src/md2.o
OBJECTS += mbed-os/features/mbedtls/src/md4.o
OBJECTS += mbed-os/features/mbedtls/src/md5.o
OBJECTS += mbed-os/features/mbedtls/src/md_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += mbed-os/features/mbedtls/src/net_sockets.o
OBJECTS += mbed-os/features/mbedtls/src/oid.o
OBJECTS += mbed-os/features/mbedtls/src/padlock.o
OBJECTS += mbed-os/features/mbedtls/src/pem.o
OBJECTS += mbed-os/features/mbedtls/src/pk.o
OBJECTS += mbed-os/features/mbedtls/src/pk_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs11.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs12.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs5.o
OBJECTS += mbed-os/features/mbedtls/src/pkparse.o
OBJECTS += mbed-os/features/mbedtls/src/pkwrite.o
OBJECTS += mbed-os/features/mbedtls/src/platform.o
OBJECTS += mbed-os/features/mbedtls/src/ripemd160.o
OBJECTS += mbed-os/features/mbedtls/src/rsa.o
OBJECTS += mbed-os/features/mbedtls/src/sha1.o
OBJECTS += mbed-os/features/mbedtls/src/sha256.o
OBJECTS += mbed-os/features/mbedtls/src/sha512.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cache.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cli.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cookie.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_srv.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ticket.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_tls.o
OBJECTS += mbed-os/features/mbedtls/src/threading.o
OBJECTS += mbed-os/features/mbedtls/src/timing.o
OBJECTS += mbed-os/features/mbedtls/src/version.o
OBJECTS += mbed-os/features/mbedtls/src/version_features.o
OBJECTS += mbed-os/features/mbedtls/src/x509.o
OBJECTS += mbed-os/features/mbedtls/src/x509_create.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crl.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509_csr.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_csr.o
OBJECTS += mbed-os/features/mbedtls/src/xtea.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/aes_alt.o
OBJECTS += mbed-os/features/netsocket/NetworkInterface.o
OBJECTS += mbed-os/features/netsocket/NetworkStack.o
OBJECTS += mbed-os/features/netsocket/Socket.o
OBJECTS += mbed-os/features/netsocket/SocketAddress.o
OBJECTS += mbed-os/features/netsocket/TCPServer.o
OBJECTS += mbed-os/features/netsocket/TCPSocket.o
OBJECTS += mbed-os/features/netsocket/UDPSocket.o
OBJECTS += mbed-os/features/netsocket/WiFiAccessPoint.o
OBJECTS += mbed-os/features/netsocket/nsapi_dns.o
OBJECTS += mbed-os/hal/mbed_gpio.o
OBJECTS += mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += mbed-os/hal/mbed_pinmap_common.o
OBJECTS += mbed-os/hal/mbed_ticker_api.o
OBJECTS += mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += mbed-os/platform/CallChain.o
OBJECTS += mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += mbed-os/platform/mbed_application.o
OBJECTS += mbed-os/platform/mbed_assert.o
OBJECTS += mbed-os/platform/mbed_board.o
OBJECTS += mbed-os/platform/mbed_critical.o
OBJECTS += mbed-os/platform/mbed_error.o
OBJECTS += mbed-os/platform/mbed_interface.o
OBJECTS += mbed-os/platform/mbed_mem_trace.o
OBJECTS += mbed-os/platform/mbed_retarget.o
OBJECTS += mbed-os/platform/mbed_rtc_time.o
OBJECTS += mbed-os/platform/mbed_semihost_api.o
OBJECTS += mbed-os/platform/mbed_stats.o
OBJECTS += mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += mbed-os/rtos/Mutex.o
OBJECTS += mbed-os/rtos/RtosTimer.o
OBJECTS += mbed-os/rtos/Semaphore.o
OBJECTS += mbed-os/rtos/Thread.o
OBJECTS += mbed-os/rtos/rtos_idle.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/HAL_CM.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC/HAL_CM4.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC/SVC_Table.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Event.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_List.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Mailbox.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_MemBox.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Memory.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Mutex.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_OsEventObserver.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Robin.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Semaphore.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_System.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Task.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Time.o
OBJECTS += mbed-os/rtos/rtx/TARGET_CORTEX_M/rt_Timer.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPins.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_stm32f4xx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_GCC_ARM/startup_stm32f411xe.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/cmsis_nvic.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogin_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/hal_init_pre.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_msp_template.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/mbed_overrides.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/serial_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_32b.o
OBJECTS += mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_32b.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I..//usr/src/mbed-sdk
INCLUDE_PATHS += -I../USBHOST
INCLUDE_PATHS += -I../USBHOST/USBHost
INCLUDE_PATHS += -I../USBHOST/USBHost/TARGET_STM
INCLUDE_PATHS += -I../USBHOST/USBHost3GModule
INCLUDE_PATHS += -I../USBHOST/USBHostHID
INCLUDE_PATHS += -I../USBHOST/USBHostHub
INCLUDE_PATHS += -I../USBHOST/USBHostMIDI
INCLUDE_PATHS += -I../USBHOST/USBHostMSD
INCLUDE_PATHS += -I../USBHOST/USBHostSerial
INCLUDE_PATHS += -I../mbed-os
INCLUDE_PATHS += -I../mbed-os/cmsis
INCLUDE_PATHS += -I../mbed-os/drivers
INCLUDE_PATHS += -I../mbed-os/events
INCLUDE_PATHS += -I../mbed-os/events/equeue
INCLUDE_PATHS += -I../mbed-os/features
INCLUDE_PATHS += -I../mbed-os/features/filesystem
INCLUDE_PATHS += -I../mbed-os/features/filesystem/bd
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I../mbed-os/features/frameworks
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/utest
INCLUDE_PATHS += -I../mbed-os/features/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/features/netsocket
INCLUDE_PATHS += -I../mbed-os/hal
INCLUDE_PATHS += -I../mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I../mbed-os/platform
INCLUDE_PATHS += -I../mbed-os/rtos
INCLUDE_PATHS += -I../mbed-os/rtos/rtx/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_GCC_ARM/STM32F411XE.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp


C_FLAGS += -std=gnu11
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_STM32F411RE
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DUSB_STM_HAL
C_FLAGS += -DTARGET_STM32F4
C_FLAGS += -DTARGET_M4
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DUSBHOST_OTHER
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DTARGET_FF_MORPHO
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTARGET_NAME=NUCLEO_F411RE
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DTARGET_STM32F411xE
C_FLAGS += -DDEVICE_ERROR_RED=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1586012560.1703427
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTARGET_NUCLEO_F411RE
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -std=gnu11
C_FLAGS += -c
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fno-delete-null-pointer-checks
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -Os
C_FLAGS += -g
C_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
C_FLAGS += -mcpu=cortex-m4
C_FLAGS += -mthumb
C_FLAGS += -mfpu=fpv4-sp-d16
C_FLAGS += -mfloat-abi=softfp

CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_STM32F411RE
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DUSB_STM_HAL
CXX_FLAGS += -DTARGET_STM32F4
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DUSBHOST_OTHER
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DTARGET_FF_MORPHO
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTARGET_NAME=NUCLEO_F411RE
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DTARGET_STM32F411xE
CXX_FLAGS += -DDEVICE_ERROR_RED=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1586012560.1703427
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTARGET_NUCLEO_F411RE
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -c
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fno-delete-null-pointer-checks
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -Os
CXX_FLAGS += -g
CXX_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
CXX_FLAGS += -mcpu=cortex-m4
CXX_FLAGS += -mthumb
CXX_FLAGS += -mfpu=fpv4-sp-d16
CXX_FLAGS += -mfloat-abi=softfp

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DUSB_STM_HAL
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DUSBHOST_OTHER
ASM_FLAGS += -I/usr/src/mbed-sdk
ASM_FLAGS += -I../USBHOST
ASM_FLAGS += -I../USBHOST/USBHost
ASM_FLAGS += -I../USBHOST/USBHost/TARGET_STM
ASM_FLAGS += -I../USBHOST/USBHost3GModule
ASM_FLAGS += -I../USBHOST/USBHostHID
ASM_FLAGS += -I../USBHOST/USBHostHub
ASM_FLAGS += -I../USBHOST/USBHostMIDI
ASM_FLAGS += -I../USBHOST/USBHostMSD
ASM_FLAGS += -I../USBHOST/USBHostSerial
ASM_FLAGS += -I../mbed-os
ASM_FLAGS += -I../mbed-os/cmsis
ASM_FLAGS += -I../mbed-os/drivers
ASM_FLAGS += -I../mbed-os/events
ASM_FLAGS += -I../mbed-os/events/equeue
ASM_FLAGS += -I../mbed-os/features
ASM_FLAGS += -I../mbed-os/features/filesystem
ASM_FLAGS += -I../mbed-os/features/filesystem/bd
ASM_FLAGS += -I../mbed-os/features/filesystem/fat
ASM_FLAGS += -I../mbed-os/features/filesystem/fat/ChaN
ASM_FLAGS += -I../mbed-os/features/frameworks
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/unity/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/utest
ASM_FLAGS += -I../mbed-os/features/frameworks/utest/utest
ASM_FLAGS += -I../mbed-os/features/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/features/netsocket
ASM_FLAGS += -I../mbed-os/hal
ASM_FLAGS += -I../mbed-os/hal/storage_abstraction
ASM_FLAGS += -I../mbed-os/platform
ASM_FLAGS += -I../mbed-os/rtos
ASM_FLAGS += -I../mbed-os/rtos/rtx/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device
ASM_FLAGS += -include
ASM_FLAGS += ../mbed_config.h
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -c
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fno-delete-null-pointer-checks
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -Os
ASM_FLAGS += -g
ASM_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
ASM_FLAGS += -mcpu=cortex-m4
ASM_FLAGS += -mthumb
ASM_FLAGS += -mfpu=fpv4-sp-d16
ASM_FLAGS += -mfloat-abi=softfp


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "$(filter %.o, $^)" > .link_options.txt
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ @.link_options.txt $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
# Catch-all

%: ;

# Catch-all
###############################################################################
